export const FETCH_DATA_PRODUCT_SUCCESS = 'FETCH_DATA_PRODUCT_SUCCESS';
export const FETCH_DATA_PRODUCT_FAIL = 'FETCH_DATA_PRODUCT_FAIL';

export const FETCH_DATA_PRODUCT_ID_SUCCESS = 'FETCH_DATA_PRODUCT_ID_SUCCESS';
export const FETCH_DATA_PRODUCT_ID_FAIL = 'FETCH_DATA_PRODUCT_ID_FAIL';
